<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         $faker = Faker\Factory::create();
        DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Mochi cánh hoa ', 
            'slug'=> 'mo-chi-canh-hoa',  
            'content' => 'Mochi cánh hoa ',
            'unit_price'=> '100000',
            'discount_price'=>'90000',
            'image'=>'canh-hoa.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Mochi dâu tươi', 
            'slug'=> 'mo-chi-dau-tuoi',  
            'content' => 'Mochi dâu tươi',
            'unit_price'=> '110000',
            'discount_price'=>'100000',
            'image'=>'dau-tuoi.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Mochi đậu đỏ', 
            'slug'=> 'mo-chi-dau-do',  
            'content' => 'Mochi đậu đỏ',
            'unit_price'=> '120000',
            'discount_price'=>'110000',
            'image'=>'dau-do.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
          DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Mochi kem', 
            'slug'=> 'michi-kem',  
            'content' => 'Mochi kem',
            'unit_price'=> '100000',
            'discount_price'=>'90000',
            'image'=>'mochi-kem.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Mochi cỏ xanh', 
            'slug'=> 'mo-chi-co-xan',  
            'content' => 'Mochi cỏ xanh',
            'unit_price'=> '100000',
            'discount_price'=>'90000',
            'image'=>'co-xanh.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Mochi đậu xanh nướng', 
            'slug'=> 'mo-chi-nuong',  
            'content' => 'Mochi đậu xanh nướng',
            'unit_price'=> '120000',
            'discount_price'=>'100000',
            'image'=>'nuong.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
            DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Mochi trà xanh', 
            'slug'=> 'tra-xanh',  
            'content' => 'Mochi trà xanh',
            'unit_price'=> '120000',
            'discount_price'=>'100000',
            'image'=>'tra-xanh.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
          DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Mochi hoa anh đào', 
            'slug'=> 'hoa-anh-dao',  
            'content' => 'Mochi hoa anh đào',
            'unit_price'=> '130000',
            'discount_price'=>'120000',
            'image'=>'anh-dao.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Bánh đậu xanh(Bánh luk chup )', 
            'slug'=> 'luk-chup',  
            'content' => 'Bánh đậu xanh(Bánh luk chup )',
            'unit_price'=> '100000',
            'discount_price'=>'90000',
            'image'=>'luk-chup.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Bánh crepe (Khanom Buang)', 
            'slug'=> 'kha-nom-buang',  
            'content' => 'Bánh crepe (Khanom Buang)',
            'unit_price'=> '135000',
            'discount_price'=>'120000',
            'image'=>'kha-nom-buang.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Bánh mè cuộn', 
            'slug'=> 'banh-me-cuon',  
            'content' => 'Bánh mè cuộn',
            'unit_price'=> '145000',
            'discount_price'=>'120000',
            'image'=>'banh-me.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Bánh lòng trứng (Kaiwan)', 
            'slug'=> 'kai-wan',  
            'content' => 'Bánh lòng trứng (Kaiwan)',
            'unit_price'=> '155000',
            'discount_price'=>'130000',
            'image'=>'kai-wan1.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Bánh Roti ', 
            'slug'=> 'banh-roti',  
            'content' => 'Bánh Roti',
            'unit_price'=> '165000',
            'discount_price'=>'150000',
            'image'=>'ro-ti.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Bánh Thạch bí ngô', 
            'slug'=> 'thach-ngo',  
            'content' => 'Bánh Thạch bí ngô',
            'unit_price'=> '185000',
            'discount_price'=>'160000',
            'image'=>'thach-ngo.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Xôi đậu ống tre (Khao lam)', 
            'slug'=> 'ong-tre',  
            'content' => 'Xôi đậu ống tre (Khao lam)',
            'unit_price'=> '175000',
            'discount_price'=>'160000',
            'image'=>'ong-tre.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);

         DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Bánh con cá', 
            'slug'=> 'banh-con-ca',  
            'content' => 'Bánh con cá',
            'unit_price'=> '185000',
            'discount_price'=>'160000',
            'image'=>'banh-ca.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Bánh gạo hình bán nguyệt', 
            'slug'=> 'banh-ban-nguyet',  
            'content' => 'Bánh gạo hình bán nguyệt',
            'unit_price'=> '135000',
            'discount_price'=>'110000',
            'image'=>'ban-nguyet.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Bánh thanh trà ', 
            'slug'=> 'banh-thanh-tra',  
            'content' => 'Bánh kem Chocolate Dâu',
            'unit_price'=> '125000',
            'discount_price'=>'115000',
            'image'=>'banh-tra.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Bánh bí ngô', 
            'slug'=> 'banh-bi-ngo',  
            'content' => 'Bánh bí ngô',
            'unit_price'=> '135000',
            'discount_price'=>'125000',
            'image'=>'bi-ngo.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Bánh gạo viên', 
            'slug'=> 'banh-gao-vien',  
            'content' => 'Bánh gạo viên',
            'unit_price'=> '115000',
            'discount_price'=>'100000',
            'image'=>'gao-vien.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Bánh hoa mơ', 
            'slug'=> 'banh-hoa-mo',  
            'content' => 'Bánh hoa mơ',
            'unit_price'=> '145000',
            'discount_price'=>'125000',
            'image'=>'hoa-mo.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Bánh mật ong ', 
            'slug'=> 'mat-ong',  
            'content' => 'Bánh mật ong',
            'unit_price'=> '175000',
            'discount_price'=>'165000',
            'image'=>'mat-ong.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         



         DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh bò thốt nốt ', 
            'slug'=> 'banh-bo-thot-not',  
            'content' => 'Bánh bò thốt nốt',
            'unit_price'=> '165000',
            'discount_price'=>'145000',
            'image'=>'banh-bo.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
          DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh đúc nước cốt dừa', 
            'slug'=> 'banh-duc',  
            'content' => 'Bánh đúc nước cốt dừa',
            'unit_price'=> '145000',
            'discount_price'=>'115000',
            'image'=>'banh-duc.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
          DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh tét mini ', 
            'slug'=> 'banh-tet-mini',  
            'content' => 'Bánh tét mini',
            'unit_price'=> '165000',
            'discount_price'=>'135000',
            'image'=>'banh-tet-mini.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh bông lan ', 
            'slug'=> 'banh-bong-lan',  
            'content' => 'Bánh bông lan',
            'unit_price'=> '205000',
            'discount_price'=>'195000',
            'image'=>'banh-kem-4.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Chocolate Fruit', 
            'slug'=> 'banh-kem-chocolate-fruit',  
            'content' => 'Bánh kem Chocolate Fruit',
            'unit_price'=> '145000',
            'discount_price'=>'130000',
            'image'=>'banh-kem-5.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Mango Mouse', 
            'slug'=> 'banh-kem-mango-mouse',  
            'content' => 'Bánh kem Mango Mouse',
            'unit_price'=> '125000',
            'discount_price'=>'120000',
            'image'=>'banh-kem-6.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
          DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Matcha Mouse', 
            'slug'=> 'banh-kem-matcha-mouse',  
            'content' => 'Bánh kem Matcha Mouse',
            'unit_price'=> '135000',
            'discount_price'=>'120000',
            'image'=>'banh-kem-6.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Flower Fruit', 
            'slug'=> 'banh-kem-flower-fruit',  
            'content' => 'Bánh kem Flower Fruit',
            'unit_price'=> '115000',
            'discount_price'=>'100000',
            'image'=>'banh-kem-7.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Strawberry Delight', 
            'slug'=> 'banh-kem-strawberry-delight',  
            'content' => 'Bánh kem Strawberry Delight',
            'unit_price'=> '185000',
            'discount_price'=>'180000',
            'image'=>'banh-kem-8.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Raspberry Delight', 
            'slug'=> 'banh-kem-raspberry-delight',  
            'content' => 'Bánh kem Raspberry Delight',
            'unit_price'=> '165000',
            'discount_price'=>'150000',
            'image'=>'banh-kem-9.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);



         DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Sầu riêng', 
            'slug'=> 'banh-crepe-sau-rieng',  
            'content' => 'Bánh Crepe Sầu riêng',
            'unit_price'=> '135000',
            'discount_price'=>'130000',
            'image'=>'banh-crepe-2.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Sầu riêng-Chuối', 
            'slug'=> 'banh-crepe-sau-rieng-chuối',  
            'content' => 'Bánh Crepe Sầu riêng-Chuối',
            'unit_price'=> '155000',
            'discount_price'=>'130000',
            'image'=>'banh-crepe-1.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Dâu', 
            'slug'=> 'banh-crepe-dau',  
            'content' => 'Bánh Crepe Dâu',
            'unit_price'=> '160000',
            'discount_price'=>'140000',
            'image'=>'banh-crepe-3.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Pháp', 
            'slug'=> 'banh-crepe-phap',  
            'content' => 'Bánh Crepe Pháp',
            'unit_price'=> '140000',
            'discount_price'=>'130000',
            'image'=>'banh-crepe-4.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
          DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Táo', 
            'slug'=> 'banh-crepe-tao',  
            'content' => 'Bánh Crepe Táo',
            'unit_price'=> '140000',
            'discount_price'=>'140000',
            'image'=>'banh-crepe-5.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Trà xanh', 
            'slug'=> 'banh-crepe-tra-xanh',  
            'content' => 'Bánh Crepe Trà xanh',
            'unit_price'=> '120000',
            'discount_price'=>'110000',
            'image'=>'banh-crepe-6.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Sầu riêng và Dứa', 
            'slug'=> 'banh-crepe-sau-rieng-va-dua',  
            'content' => 'Bánh Crepe Sầu riêng và Dứa',
            'unit_price'=> '140000',
            'discount_price'=>'135000',
            'image'=>'banh-crepe-7.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);

           DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Chocolate', 
            'slug'=> 'banh-crepe-chocolate',  
            'content' => 'Bánh Crepe Sầu riêng và Dứa',
            'unit_price'=> '140000',
            'discount_price'=>'135000',
            'image'=>'banh-crepe-8.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Đào', 
            'slug'=> 'banh-crepe-dao',  
            'content' => 'Bánh Crepe Đào',
            'unit_price'=> '130000',
            'discount_price'=>'125000',
            'image'=>'banh-crepe-9.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);


            DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'Thạch rau câu phô mai', 
            'slug'=> 'pho-mai',  
            'content' => 'Thạch rau câu phô mai',
            'unit_price'=> '80000',
            'discount_price'=>'60000',
            'image'=>'pho_mai1.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
             DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'Thạch rau câu sơn thủy ', 
            'slug'=> 'son-thuy',  
            'content' => 'Thạch rau câu sơn thủy',
            'unit_price'=> '100000',
            'discount_price'=>'90000',
            'image'=>'son_thuy.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
              DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'Thạch rau câu dưa hấu', 
            'slug'=> 'dua-hau',  
            'content' => 'Thạch rau câu dưa hấu',
            'unit_price'=> '100000',
            'discount_price'=>'90000',
            'image'=>'dua_hau.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
             DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'Thạch rau câu bắp', 
            'slug'=> 'thach-bap',  
            'content' => 'Thạch rau câu bắp',
            'unit_price'=> '100000',
            'discount_price'=>'90000',
            'image'=>'bap.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
               DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'Thạch rau câu cafe', 
            'slug'=> 'ca-fe',  
            'content' => 'Thạch rau câu cafe',
            'unit_price'=> '100000',
            'discount_price'=>'90000',
            'image'=>'ca_fe.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
             DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'Thạch rau câu 3D hình bông', 
            'slug'=> 'hinh-bong',  
            'content' => 'Thạch rau câu 3D hình bông',
            'unit_price'=> '150000',
            'discount_price'=>'140000',
            'image'=>'bong_3d.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
              DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'Thạch rau câu trái cây', 
            'slug'=> 'trai-cay',  
            'content' => 'Thạch rau câu trái cây',
            'unit_price'=> '185000',
            'discount_price'=>'1750000',
            'image'=>'trai_cay.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);



            DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Nước ép dâu ', 
            'slug'=> 'nuoc-ep-dau',  
            'content' => 'Nước ép dâu',
            'unit_price'=> '32000',
            'discount_price'=>'35000',
            'image'=>'ep-dau.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
            DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Nước ép thơm', 
            'slug'=> 'nuoc-ep-thom',  
            'content' => 'Nước ép thơm',
            'unit_price'=> '32000',
            'discount_price'=>'35000',
            'image'=>'ep-thom.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Nước ép dưa hấu', 
            'slug'=> 'nuoc-ep-dua-hau',  
            'content' => 'Nước ép dưa hấu',
            'unit_price'=> '32000',
            'discount_price'=>'35000',
            'image'=>'ep-hau.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
            DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Nước ép lựu ', 
            'slug'=> 'nuoc-luu',  
            'content' => 'Nước ép lựu',
            'unit_price'=> '32000',
            'discount_price'=>'35000',
            'image'=>'lu.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
             DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Nước ép táo ', 
            'slug'=> 'nuoc-ep-tao',  
            'content' => 'Nước ép táo',
            'unit_price'=> '32000',
            'discount_price'=>'35000',
            'image'=>'ep-tao.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
             DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Nước rau má', 
            'slug'=> 'nuoc-rau-ma',  
            'content' => 'Nước rau má',
            'unit_price'=> '32000',
            'discount_price'=>'35000',
            'image'=>'rau-ma.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Nước ép mix thơm cà rốt ', 
            'slug'=> 'mix-thom-carot',  
            'content' => 'Nước ép mix thơm cà rốt',
            'unit_price'=> '32000',
            'discount_price'=>'35000',
            'image'=>'thom-carot.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Nước ép nho ', 
            'slug'=> 'nuoc-ep-nho',  
            'content' => 'Nước ép nho',
            'unit_price'=> '32000',
            'discount_price'=>'35000',
            'image'=>'ep-nho.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Nước ép dưa gang', 
            'slug'=> 'nuoc-ep-dua-gang',  
            'content' => 'Nước ép dưa gang',
            'unit_price'=> '32000',
            'discount_price'=>'35000',
            'image'=>'dua-gang.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
    }
}
